
import difflib
import re
from enum import Enum

class DatabaseType(Enum):
    consumer = 1
    business = 2
    cellphone = 3
    newbusiness = 4
#print(DatabaseType(1).name) >>> consumer

def normalize_state(state_name: str, lookup_data: dict) -> str | None:
    """
    Returns the official abbreviation of a state.
    Tolerates slight spelling errors or use of full state names.
    """
    if not state_name or not isinstance(state_name, str):
        return None

    # Basic cleanup
    state_name = state_name.strip().lower().replace(".", "")

    # Extract data from the JSON
    entries = lookup_data["Response"]["responseDetails"]["RefLookUpDetails"]
    name_to_abbr = {e["field"].strip().lower(): e["value"] for e in entries}
    abbr_set = {e["value"].upper() for e in entries}

    # If it's already a valid abbreviation
    if state_name.upper() in abbr_set:
        return state_name.upper()

    # Exact match by name
    if state_name in name_to_abbr:
        return name_to_abbr[state_name]

    # Approximate match
    possibles = list(name_to_abbr.keys())
    matches = difflib.get_close_matches(state_name, possibles, n=1, cutoff=0.8)
    if matches:
        return name_to_abbr[matches[0]]

    return None

def normalize_gender(value: str) -> str | None:
    """
    Normalizes the gender value for the DataIRIS API.
    Accepts 'M', 'F', 'male', 'fe' etc.
    Returns 'M', 'F', or None.
    """
    if not value or not isinstance(value, str):
        return None

    genero = value.strip().lower()

    masculino = {"m", "male", "mal", "ma"}
    femenino = {"f", "female", "femal", "fe"}

    if genero in masculino:
        return "M"
    elif genero in femenino:
        return "F"

    return None


def clean_text(text: str) -> str:
    """Removes spaces, periods, and non-alphabetic characters"""
    if not text or not isinstance(text, str):
        return ""
    return re.sub(r"[^a-zA-Z]", "", text)


def extract_initial(text: str) -> str | None:
    """Returns only the first cleaned letter"""
    cleaned = clean_text(text)
    return cleaned[0] if cleaned else None


lookup_data_state = {'Response': {'responseCode': '200',
  'responseMessage': 'Success',
  'responseDetails': {'RefLookUpDetails': [{'database': 'consumer',
     'search': 'physical_state',
     'field': 'Alabama',
     'child': '',
     'value': 'AL',
     'displayValue': 'Alabama',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Alaska',
     'child': '',
     'value': 'AK',
     'displayValue': 'Alaska',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Arizona',
     'child': '',
     'value': 'AZ',
     'displayValue': 'Arizona',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Arkansas',
     'child': '',
     'value': 'AR',
     'displayValue': 'Arkansas',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'California',
     'child': '',
     'value': 'CA',
     'displayValue': 'California',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Colorado',
     'child': '',
     'value': 'CO',
     'displayValue': 'Colorado',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Connecticut',
     'child': '',
     'value': 'CT',
     'displayValue': 'Connecticut',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Delaware',
     'child': '',
     'value': 'DE',
     'displayValue': 'Delaware',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'District of Columbia',
     'child': '',
     'value': 'DC',
     'displayValue': 'District of Columbia',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Florida',
     'child': '',
     'value': 'FL',
     'displayValue': 'Florida',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Georgia',
     'child': '',
     'value': 'GA',
     'displayValue': 'Georgia',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Hawaii',
     'child': '',
     'value': 'HI',
     'displayValue': 'Hawaii',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Idaho',
     'child': '',
     'value': 'ID',
     'displayValue': 'Idaho',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Illinois',
     'child': '',
     'value': 'IL',
     'displayValue': 'Illinois',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Indiana',
     'child': '',
     'value': 'IN',
     'displayValue': 'Indiana',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Iowa',
     'child': '',
     'value': 'IA',
     'displayValue': 'Iowa',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Kansas',
     'child': '',
     'value': 'KS',
     'displayValue': 'Kansas',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Kentucky',
     'child': '',
     'value': 'KY',
     'displayValue': 'Kentucky',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Louisiana',
     'child': '',
     'value': 'LA',
     'displayValue': 'Louisiana',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Maine',
     'child': '',
     'value': 'ME',
     'displayValue': 'Maine',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Maryland',
     'child': '',
     'value': 'MD',
     'displayValue': 'Maryland',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Massachusetts',
     'child': '',
     'value': 'MA',
     'displayValue': 'Massachusetts',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Michigan',
     'child': '',
     'value': 'MI',
     'displayValue': 'Michigan',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Minnesota',
     'child': '',
     'value': 'MN',
     'displayValue': 'Minnesota',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Mississippi',
     'child': '',
     'value': 'MS',
     'displayValue': 'Mississippi',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Missouri',
     'child': '',
     'value': 'MO',
     'displayValue': 'Missouri',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Montana',
     'child': '',
     'value': 'MT',
     'displayValue': 'Montana',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Nebraska',
     'child': '',
     'value': 'NE',
     'displayValue': 'Nebraska',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Nevada',
     'child': '',
     'value': 'NV',
     'displayValue': 'Nevada',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'New Hampshire',
     'child': '',
     'value': 'NH',
     'displayValue': 'New Hampshire',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'New Jersey',
     'child': '',
     'value': 'NJ',
     'displayValue': 'New Jersey',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'New Mexico',
     'child': '',
     'value': 'NM',
     'displayValue': 'New Mexico',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'New York',
     'child': '',
     'value': 'NY',
     'displayValue': 'New York',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'North Carolina',
     'child': '',
     'value': 'NC',
     'displayValue': 'North Carolina',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'North Dakota',
     'child': '',
     'value': 'ND',
     'displayValue': 'North Dakota',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Ohio',
     'child': '',
     'value': 'OH',
     'displayValue': 'Ohio',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Oklahoma',
     'child': '',
     'value': 'OK',
     'displayValue': 'Oklahoma',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Oregon',
     'child': '',
     'value': 'OR',
     'displayValue': 'Oregon',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Pennsylvania',
     'child': '',
     'value': 'PA',
     'displayValue': 'Pennsylvania',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Rhode Island',
     'child': '',
     'value': 'RI',
     'displayValue': 'Rhode Island',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'South Carolina',
     'child': '',
     'value': 'SC',
     'displayValue': 'South Carolina',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'South Dakota',
     'child': '',
     'value': 'SD',
     'displayValue': 'South Dakota',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Tennessee',
     'child': '',
     'value': 'TN',
     'displayValue': 'Tennessee',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Texas',
     'child': '',
     'value': 'TX',
     'displayValue': 'Texas',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Utah',
     'child': '',
     'value': 'UT',
     'displayValue': 'Utah',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Vermont',
     'child': '',
     'value': 'VT',
     'displayValue': 'Vermont',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Virginia',
     'child': '',
     'value': 'VA',
     'displayValue': 'Virginia',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Washington',
     'child': '',
     'value': 'WA',
     'displayValue': 'Washington',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'West Virginia',
     'child': '',
     'value': 'WV',
     'displayValue': 'West Virginia',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Wisconsin',
     'child': '',
     'value': 'WI',
     'displayValue': 'Wisconsin',
     'defaultSelection': False},
    {'database': 'consumer',
     'search': 'physical_state',
     'field': 'Wyoming',
     'child': '',
     'value': 'WY',
     'displayValue': 'Wyoming',
     'defaultSelection': False}]}}}

